### ISSUE TITLE
Idea: use term "metro" for maven artefact?

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/metro-wsit#147]
Currently the project uses multiple terms:

* metro
* wsit
* webservices
* webservices-osgi

There's also various combinations of these terms. Specifically the main artefact is
`org.glassfish.metro:webservices-osgi`.

To be more aligned with many other project names and artefact names, what about changing this to simply"

`org.glassfish.metro:metro`

?

**Comment by lukasj** [comment]
End-user facing artifact are `org.glassfish.metro:metro-standalone` and sub-set of `org.glassfish.metro:webservices-*` artifacts for particular use-case (SE/EE; tomcat/GF; eventually OSGi). All this is documented in [the userguide](https://eclipse-ee4j.github.io/metro-wsit/3.0.0/guide/ch02.html#using-mavenized-metro-binaries)

**Comment by arjantijms** [comment]
> All this is documented in the userguide

Can't we update the userguide then? Having a `org.glassfish.metro:metro` including OSGi data would perhaps be a bit of a better name. E.g. we also have `org.glassfish.soteria:soteria` and `org.glassfish.wasp:wasp` which include OSGi data.

**Comment by lukasj** [comment]
what exactly should `org.glassfish.metro:metro` artifact contain? Take into account that Metro as such is a collection of ~25 different jar files from ~11 repositories - this excludes dependencies on other projects, like grizzly, gmbal, pfl, various jakarta APIs, tomcat APIs or even GF APIs where some of them are required and currently repackaged in webservices-rt and webservices-extra while not included in webservices-osgi, since GF already contains them (ie pfl). The only reason webservices-osgi.jar exists is GlassFish - that used to be the primary and for the long time the only - consumer of this artifact; apart from performance reasons (likely not valid anymore), having everything GF needs in just one file  - or small number of files - has been proven by time to make integrations, testing, patching easier. (note that ability to patch pieces of metro is also the reason why jaxb-ri is not part of webservices-osgi.jar)

edit: at the highest level (Metro = jaxb-ri + jaxws-ri + wsit)

**Comment by arjantijms** [comment]
> what exactly should org.glassfish.metro:metro artifact contain? 

The same things that org.glassfish.metro:webservices-osgi contains. So just a rename.
